### PR TITLE
Add travis-ci

### PR DESCRIPTION
**Pull request by a1ien**
For check that PR compile.

You need just enable https://travis-ci.com/
Status for this PR
https://travis-ci.com/a1ien/dbus-rs/builds/121546152
By now travis have bug. And with use ubuntu 16.04 instead 18.04. When this fix we can uncomment last line for run test.

### CODE REVIEW

**Comment by a1ien** [comment]
I thought about turning it on cash. But since we still have one simple, I don’t see a big advantage. But I can add.

**Comment by Ichimonji10** [comment]
I just did a quick empirical test to see how caching affects certain commands on one of my own personal projects:

* `cargo check`: 6s vs 1m 12s
* `cargo test`: 16s vs 1m 17s

See [with caching](https://travis-ci.org/Ichimonji10/killjoy/jobs/566252442#L235-L243) and [without caching](https://travis-ci.org/Ichimonji10/killjoy/jobs/566641803#L238-L367).

I didn't compare the total build time with and without caching, as in my experience, Travis CI build times tend to vary quite a bit.

**Comment by diwic** [comment]
Is it possible to run `cargo test` now that the `dbus-tokio` error is fixed up (and why are default features disabled?)

**Comment by a1ien** [comment]
We can't run `cargo test` now. Because now travis uses the wrong VM for rust.
https://travis-ci.community/t/for-dist-bionic-xenial-vm-is-used-instead-with-language-rust/4487
And we need 1.12 libdbus for `dbus_try_get_local_machine_id` but xenial use 1.10. Abd bionic have 1.12 dbus.

Log with enabled `cargo test` on travis

**Comment by a1ien** [comment]
Removed `no-default-features`. They not need in our case.

**Comment by diwic** [comment]
Ok. Actually I want the code to run on xenial so I'll look into if it's possible to not use `dbus_try_get_local_machine_id`.

**Comment by diwic** [comment]
Ok, I just pushed a commit that makes us use `dbus_get_local_machine_id` instead. Want to try again?

**Comment by a1ien** [comment]
Now all test passed on travis
https://travis-ci.com/a1ien/dbus-rs/builds/121817547
I change PolicyKit to hostname1 for Props test

**Comment by diwic** [comment]
Okay...so I tried setting this up...and it worked fine at first, then I coded some more and now the CI is broken again, because the environment in the CI is different from my working machine. 

Any idea of a D-Bus service that implements Peer on the travis CI?

**Pull request merged**
