### PR TITLE
crossroads: Make sure get_children() with direct_only flag works correctly

### PR DESCRIPTION
**Pull request by linuxmetel**
Fixes: #412

### CODE REVIEW

**Comment by diwic** [comment]
Hi and thanks for the PR! It won't work though because it is common practice to have, say objects at `/a/b/c` without also having objects at `/a` and `/a/b`. So `a/b/c` must show up when introspecting `/`.

**Comment by diwic** [comment]
Fixed in https://github.com/diwic/dbus-rs/commit/d913c608c692af6d8cdbad397cae38727c5ff4f8

**Comment by linuxmetel** [comment]
@diwic
Oh, I see.

But when an object has more than one child, `prev` is not always the parent of `c` . So it's probably required to trace the paths which could be ancestors (ex. `/` , `/a` and `/a/b` for `/a/b/c` ) and check if it exists.

**Comment by linuxmetel** [comment]
I'm sorry. I sent mention because of my misunderstanding. (I deleted the message)
I think that it correctly works. Thank you.

**Pull request closed without merging**
