### PR TITLE
Allow signal_match_mode to be set for dbus-tokio connections

### LINKED ISSUE #346: If multiple match rules match a message, it only gets sent to the first one
If I call ` dbus::nonblock::SyncConnection::add_match` two or more times, either with the same `MatchRule` or with `MatchRule`s which match some of the same messages, and then there is a message which both of them match, I would expect both callbacks or message streams to get the message. Instead, only the first one gets it.

It looks like the bug is in `Process::process_one`, which only ever sends the message to one callback. I don't understand why it needs to remove the matching filter (with `remove_matching`) and then add it back in after calling the callback, but in any case it should be doing this for all matching filters rather than just the first one.

### PR DESCRIPTION
**Pull request by qwandor**
I missed this in #351 unfortunately. Actually fixes #346 this time.

### CODE REVIEW

**Comment by qwandor** [comment]
This is a breaking API change for `dbus-tokio` because it adds a new parameter to existing functions. If you'd rather I added new functions for each variant I can do that again, but it ends up being a lot of different variations on almost the same thing. Unfortunately it's also a breaking change for `dbus` because I had to move the `set_signal_match_mode` method to a trait.

**Comment by diwic** [comment]
What if we instead made `pub fn set_signal_match_mode` take a `&self` instead of a `&mut self`? That would not be a breaking change, and people could call `set_signal_match_mode` on the `Arc<LocalConnection>` or `Arc<SyncConnection>`, so you would not need to add anything to the trait either. 

This would mean changing the `all_signal_matches` variable from a `bool` to a `Cell<bool>` or `AtomicBool`, but that is not much of a problem either.

**Comment by qwandor** [comment]
That might work. I'll have a try tomorrow.

**Comment by qwandor** [comment]
Done, PTAL. Thanks for the suggestion, I think this is a better approach.

**Comment by diwic** [comment]
Yeah, this is much less invasive. Looks good except for the ordering, either do acquire for load and release for store, or relaxed for both.

**Comment by qwandor** [comment]
Done.

**Comment by diwic** [comment]
@qwandor Okay, but have you tested it enough now to know that there aren't more things that need to go into that release to solve your problem?

**Comment by qwandor** [comment]
I thought I had, but it turns out I introduced a bug when I was cleaning up. Sending another PR.

**Pull request merged**
