### PR TITLE
Remove the metadeps dependency and bump version

### PR DESCRIPTION
**Pull request by Eijebong**
Just use the pkg_config package directly instead of using the metadeps
one which requires an old version of toml.

cc @nox

### CODE REVIEW

**Comment by diwic** [comment]
Could you elaborate?
I believe the metadeps dependency was added for a reason, is that reason no longer relevant? 

cc @joshtriplett

**Comment by nox** [comment]
toml 0.4 depends on serde 1.0, and some people don't want to have to compile serde for their project. This means that metadeps is staying on toml 0.2 to avoid the serde dependency, and any project that uses toml 0.4 and metadeps now need to compile 2 toml parsers.

metadeps exist to be able to specify system dependencies in a declarative way, but AFAIK no other tool was ever made to read them anyway, so I don't think that's worth the compiling 2 toml parsers for no reason.

**Comment by diwic** [comment]
Hmm, so I believe @joshtriplett had some idea that this would be helpful for Debian packaging tools. I'm a little hesitant about removing it just like that.

Also, if people have a problem with metadeps, it should be fixed in metadeps: e g by adding some feature that controls what version of the toml crate that metadeps depends on?

**Comment by Eijebong** [comment]
Is there any way to move this forward ?
I don't see how that would help debian packaging tools btw, those are working with patches anyway. Changing the required version or the version name for a lib would be the same effort if you have to change the Cargo.toml file or the build.rs one

**Comment by diwic** [comment]
Ok, I've filed https://github.com/joshtriplett/metadeps/issues/9 - let's see what that gives us.

**Comment by diwic** [comment]
@nox 

 > no other tool was ever made to read them anyway

So I believe the tool that uses this info is [debcargo](https://crates.io/crates/debcargo) ?

**Pull request closed without merging**
