### PR TITLE
objpath: implement support for annotations

### PR DESCRIPTION
**Pull request by mathstuf**
Properties, methods, and signals may all contain properties according to
the spec. In fact, there are standard properties used to indicate
whether symbols are deprecated, whether a method has no reply, or when a
property signal is emitted for changed properties.

### CODE REVIEW

**Comment by mathstuf** [comment]
One question is whether `::new` for each struct should have an annotation argument (bumping the version number).

**Comment by mathstuf** [comment]
Also makes me wonder if property read/write methods should take a `Connection` to emit the `org.freedesktop.DBus.Properties.PropertiesChanged` signal.

**Comment by diwic** [comment]
This looks really good, so I merged it, thanks!

 > One question is whether ::new for each struct should have an annotation argument (bumping the version number).

Maybe a builder approach would be good for this scenario? (I e, `annotate(self) -> Self` or possibly `annotate(&mut self) -> &mut Self`) 
You can add that as a separate pull request if you like the idea.

 > Also makes me wonder if property read/write methods should take a Connection to emit the org.freedesktop.DBus.Properties.PropertiesChanged signal.

Yeah, I've been talking about the `PropertiesChanged` signal in some other issues. But I doubt this is the right approach? I believe the most common case for wanting to send a `PropertiesChanged` signal is when a property is changed locally and you want to inform the other side. It might very well be read-only to the other side. In that case, no method is called.

**Comment by mathstuf** [comment]
Ah, yes, a builder approach would be good for this. In fact, that might be good for arguments and such as well…would get rid of lots of unnamed `vec![]` arguments scattered about.

**Comment by diwic** [comment]
I've started sketching on a builder approach now.

**Comment by diwic** [comment]
Ok, so I've now started rewriting the `obj` module to fix this and many other things. It uses a builder approach for annotations and a lot of other things. It's still WIP and does not fully work yet, but you can have a look at the new `mdisp` module if you're curious.

**Pull request merged**
