### PR TITLE
crossroads: Extend testing to cover async multi-interface GetAll

### PR DESCRIPTION
**Pull request by zevweiss**
This test currently fails.

### CODE REVIEW

**Comment by zevweiss** [comment]
See https://github.com/diwic/dbus-rs/issues/414.

**Comment by diwic** [comment]
Indirectly merged into master (after fixing it up - remember that tests run in parallel so bus names cannot be reused). Thanks for submitting your bug as a test case!

**Comment by zevweiss** [comment]
Ah, I hadn't been aware the tests were parallelized, thanks.

However, diffing between commits ea1d92b (this PR) and a346ee378363 (the one that was merged) I don't see any differences in the test added here -- might an intended change have been omitted by mistake?

**Comment by diwic** [comment]
@zevweiss it was fixed up in https://github.com/diwic/dbus-rs/commit/007b0404f6a5bc298e9561c84ad39ab23d6f35b9

**Pull request closed without merging**
