### PR TITLE
dbus: Create message from `MethodErr`

### PR DESCRIPTION
**Pull request by sbwtw**
new API: `method_error` in Message

Create a new `Message` from `MethodErr`

### CODE REVIEW

**Comment by diwic** [comment]
Hmm, in general this is done internally in `Tree::handle`. I don't mind adding a public API for it, just curious why you need it?

**Comment by diwic** [comment]
Also, I would prefer if `MethodErr` had a `to_message_reply` method instead - so the tree module depends on the "base" stuff in the root but not the other way around.

**Comment by sbwtw** [comment]
I need dynamic add or remove object path from a `Tree`, and for insert, the new ObjectPath should be return. Like https://github.com/diwic/dbus-rs/issues/52 or https://github.com/diwic/dbus-rs/issues/115 . 
So I write a new struct and implements `MsgHandler` to do this. in DBus method call, return a empty `Result`, and in handler, create and insert new ObjectPath, then write this path to real HandlerResult. 
When ObjectPath insert failed, need to return a MethodError, so I need a easy way to convert this MethodError to a simple Message

**Comment by diwic** [comment]
Can't claim I fully understand what you want to do, but anyhow, I've added a `MethodErr::to_message` that I hope solves your problem.

**Pull request closed without merging**
